### PR TITLE
[WIP] Fix logout link

### PR DESCRIPTION
**Pull request by maeve**
There are a number of changes here:

* Updated the dependency on [G5/g5_authenticatable](https://github.com/G5/g5_authenticatable) to pick up changes for single sign-out.
* The logout link now points to the local logout endpoint, not the global logout on the auth server
* Added the logout link to the application layout, so you can logout from every page in the app (previously, only the ActiveAdmin pages had a logout link).
* Added local helpers for` new_user_session_path` and `destroy_user_session_path`, because ActiveAdmin does not play nicely with route helpers from a namespaced Rails engine (e.g. `g5_authenticatable.destroy_user_session_path`).
* The ActiveAdmin clients index page is now under test, but I did not create any tests for the other ActiveAdmin resources. Baby steps.
* Generally speaking, I'm trying to separate tests around user behavior (feature specs) from API-level tests (request specs). Because of the nature of microformats, all of these tests had previously been shoved into the request specs. This is a confusing and non-standard use of the spec structure. It seems like the test cases for these two types of users (human vs API client) are different enough to merit separate specs, even though the code being tested is the same.

### CODE REVIEW

**Comment by maeve** [comment]
Marked as WIP, as I'm going to split this into smaller PRs (starting with a new branch for replacing selenium-webdriver with poltergeist).

**Comment by maeve** [comment]
The changes related to updating the g5_authenticatable gem and replacing selenium-webdriver with poltergeist have been extracted into #123.

**Comment by jcstringer** [comment]
@maeve is this PR still WIP or can it be merged in?

**Comment by maeve** [comment]
@jcstringer Parts of this have already been merged in with other PRs. I'm closing this and create a new PR for the remaining changes.

**Pull request closed without merging**
