### PR TITLE
Update Inventory ETL - 85571718

### PR DESCRIPTION
**Pull request by ramontayag**
https://www.pivotaltracker.com/story/show/85571718

We also took the opportunity to refactor the code to make it easier to add new URLs to update.

### CODE REVIEW

**Comment by jpmoral** [comment]
:accept:

**Comment by ramontayag** [comment]
@jcstringer @perryqh mind reviewing this?

**Comment by jcstringer** [comment]
:ship:  nice refactor guys

**Comment by perryqh** [comment]
:+1:

**Pull request merged**
