### PR TITLE
Add cxm, cls, and dsh to updatable

### PR DESCRIPTION
**Pull request by bbauer**
For CLS/CXM/DSH apps, run updatable when...

~~a new app is deployed,~~
- [x] client/location info changes on the hub

### CODE REVIEW

**Comment by bbauer** [comment]
@variousred where do you see this calling the CMS?

**Comment by variousred** [comment]
@bbauer  nm, i thought that it had been added to the array

**Comment by variousred** [comment]
:shipit:

**Comment by bbauer** [comment]
I'm not sure the first task is possible. We could create a post deploy script that runs ```rake g5_updatable:load_all```, BUT, it looks like all auth variables must be setup before g5_updatable can actually run...https://github.com/G5/g5_updatable#installation. As of right now we aren't (can't?) programmatically setup auth when a new app is deployed.

**Pull request merged**
