### PR TITLE
Sslonly 89246028

### PR DESCRIPTION
**Pull request by variousred**
@levibrown @bbauer 
we need to know when to add rewrite rules to the .htaccess file in compiled location sites.
See this herokou support issue related to this: 
https://help.heroku.com/tickets/215860
It also allows to force https

### CODE REVIEW

**Comment by variousred** [comment]
@levibrown @bbauer

**Comment by riverblufftrail** [comment]
@variousred This is great. Is there a test constellation where I can test this out or should you just merge this?

**Comment by variousred** [comment]
@riverblufftrail i was trying to find the CMS that the g5-clw-6iy7cyq-west-denver-ivy location existed under, but there is no reocrd of that location in the hub

**Comment by variousred** [comment]
@riverblufftrail i would like to test it out there before merging

**Pull request merged**
