### PR TITLE
No Deploy location status; G5 Internal client flag

### PR DESCRIPTION
**Pull request by thescubageek**
* Adds a new status option to location - No Deploy - which will be used to prevent deployment of websites (VERY useful for redesigns)
* Adds new flag to Client model - g5_internal - which is used to denote internal testing clients versus actual paying clients

Used by CMS PR: https://github.com/g5search/g5-content-management-system/pull/755
Used by Orion CMS PR: G5/orion-cms#39

### CODE REVIEW

**Comment by jcstringer** [comment]
:ship:

**Comment by thescubageek** [comment]
Still need help getting the g5_internal var to submit to the client... not ready for primetime

**Comment by thescubageek** [comment]
All wired up correctly now, also added Deleted status as per Product's request

**Pull request merged**
